config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :users, only: [:new, :create, :show]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  resources :articles, only:[:new, :create, :show]
  resources :votes, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :body, :category, presence: true
  belongs_to :user
  belongs_to :category
  has_many :votes, dependent: :destroy
  has_one_attached :image
  validate :image_type
  def image_type
    if image.attached? && !image.content_type.in?(%('image/jpeg image/png'))
      errors.add(:image, 'Image should be a JPEG or a PNG!')
    elsif image.attached? == false
      errors.add(:image, 'You must have an image!')
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 20 }
  before_save { name.downcase! }
  has_many :articles, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_secure_password
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :article, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :popular_article, :recent_article, :list_categories,
                :homepage_background, :article_info, :truncate_body
  def list_categories
    Category.all.order(priority: :desc)
  end

  def popular_article
    Article.where(votes_count: Article.maximum(:votes_count)).first
  end

  def recent_article(category)
    category.articles.last
  end

  def homepage_background
    render partial: 'article_back' unless popular_article.nil?
  end

  def article_info
    render partial: 'article_container' if @articles.exists?
  end

  def truncate_body(article)
    article.body.split.first(6).join(' ')
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ApplicationHelper
  before_action :set_user, only: %i[new create]
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = 'Article published successfully!'
      redirect_to root_path
    else
      redirect_to new_article_path
      flash[:error] = @article.errors.full_messages.to_sentence
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :category_id, :image, :user_id)
  end

  def set_user
    redirect_to login_path unless logged_in?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include ApplicationHelper
  before_action :require_admin, except: [:show]
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categrory_params)
    if @category.save
      flash[:notice] = 'Category created successfully!'
      redirect_to root_path
    else
      redirect_to new_category_path
      flash[:error] = @category.errors.full_messages.to_sentence
    end
  end

  def show
    @category = Category.includes(:articles).find(params[:id])
    @articles = @category.articles.includes(:votes).order(created_at: :desc)
  end

  private

  def categrory_params
    params.require(:category).permit(:name)
  end

  def require_admin
    redirect_to root_path unless logged_in? && current_user.admin?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(name: params[:session][:name].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Welcome back!'
      redirect_to root_path
    else
      flash.now[:error] = 'User does not exist. You need to sign up!'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    @user = nil
    redirect_to root_path, notice: 'You have successfully logged out.' if @user.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Welcome to Roshan Life!'
      redirect_to root_path
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @vote = Vote.find_or_create_by(user_id: params[:user_id], article_id: params[:article_id])
    redirect_to request.referrer, notice: 'Voted'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    current_user ? true : false
  end

  def current_user
    @current_user ||= session[:user_id] ? User.find(session[:user_id]) : false
  end

  def check_article(category)
    render partial: 'article_title', locals: { category: category } if category.articles.exists?
  end

  def already_voted?(article)
    current_user.votes.pluck(:article_id).include?(article.id)
  end

  def show_vote(article)
    render partial: 'votes/vote_form', locals: { article: article } if logged_in? && !already_voted?(article)
  end

  def login_link
    render partial: 'layouts/login' unless logged_in?
  end

  def register_link
    render partial: 'layouts/register' unless logged_in?
  end

  def category_link
    render partial: 'layouts/category_create' if logged_in? && current_user.admin?
  end

  def article_link
    render partial: 'layouts/article_create' if logged_in? && !current_user.admin?
  end

  def logout_link
    render partial: 'layouts/logout' if logged_in?
  end

  def show_msg(key, msg)
    if flash[:error]
      render partial: 'layouts/flash_error', locals: { key: key, msg: msg }
    else
      render partial: 'layouts/flash_success', locals: { key: key, msg: msg }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/articles/new.html.erb
<div class = 'background', style="background-image: url(<%= asset_path 'lifestyle.jpg' %>)";>
  <div class = 'container'>
    <div class = 'row justify-content-center'>
      <div class = 'col-10'>
        <%= form_with(model: @article, class: 'shadow p-3 mb-3 bg-secondary rounded article-form', local: true) do |f|%>
          <div class = 'form-group row'>
            <%= f.label :title, class: 'col-2 col-form-label text-light'%>
            <div class = 'col-10'>
              <%= f.text_field :title, class: 'form-control shadow rounded', placeholder: 'Enter title here'%>
            </div>
          </div>
          <div class = 'form-group row'>
            <%= f.label :body, class: 'col-2 col-form-label text-light'%>
            <div class = 'col-10'>
              <%= f.text_area :body, rows: 10, class: 'form-control shadow rounded'%>
            </div>
          </div>
          <div class = 'form-group row'>
            <%= f.label :category, class: 'col-2 col-form-label text-light'%>
            <div class = 'col-10'>
              <%= f.collection_select(:category_id, Category.all, :id, :name)%>
            </div>
          </div>
          <div class = 'form-group row'>
            <%= f.label :image, class: 'col-2 col-form-label text-light' %>
            <div class = 'col-10'>
              <%= f.file_field :image, direct_upload: true %>
            </div>
          </div>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <div class = 'form-group row justify-content-center'>
            <%= f.submit class: 'btn btn-outline-light btn-lg' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class = 'mt-5 container bg-secondary h-100 article-face'>
  <h1 class = 'text-center pt-5'><%= @article.title %></h1>
  <p class = 'text-center mt-5'>
    <%= @article.body %>
  </p>
</div>

app/views/categories/_article_container.html.erb
  <div class = 'article-container'>
    <% @articles.each do |article| %>
      <div class = 'box-article d-flex p-0'>
        <div class = 'article-image', style="background-image: url(<%=url_for(article.image)%>)";>
        </div>
        <div class = 'article-text'>
          <h2 class = 'pl-2'><%= link_to article.title, article, class: 'article-head' %></h2>
          <p class = 'article-body pl-2'><%= truncate_body(article) %></p>
            <%= show_vote(article) %>
          <h3 class = 'article-author pb-0 pl-2'>By <%= article.user.name.capitalize %></h3>
        </div>
      </div>
    <% end %>
  </div>

app/views/categories/new.html.erb
<div class = 'background', style="background-image: url(<%= asset_path 'lifestyle.jpg' %>)";>
  <div class = 'container new-category'>
    <div class = 'row justify-content-center'>
      <div class = 'col-10'>
        <%= form_with(model: @category, class: 'shadow forms bg-secondary', local: true) do |f|%>
          <div class = 'form-group row'>
            <%= f.label :name, class: 'col-2 col-form-label text-light'%>
            <div class = 'col-10'>
              <%= f.text_field :name, class: 'form-control shadow rounded', placeholder: 'Enter name for Category'%>
            </div>
          </div>
          <div class = 'form-group row justify-content-center'>
            <%= f.submit class: 'btn btn-outline-light btn-lg' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<%= article_info %>

app/views/layouts/_article_create.html.erb
<%= link_to 'CREATE ARTICLE', new_article_path %> |

app/views/layouts/_category_create.html.erb
<%= link_to 'CREATE CATEGORY', new_category_path %> |

app/views/layouts/_flash_error.html.erb
<div class="alert alert-danger mb-0"<%= key %> alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= msg %>
</div>

app/views/layouts/_flash_style.html.erb
<% flash.each do |key, msg| %>
  <div class = 'text-center'>
    <%= show_msg(key, msg) %>
  </div>
<% end %>

app/views/layouts/_flash_success.html.erb
<div class="alert alert-success mb-0"<%= key %> alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= msg %>
</div>

app/views/layouts/_footer.html.erb
<footer class = 'p-lg-2'>
  <%= link_to root_path do %>
    <%= image_tag "my_logo1.jpg" %>
  <% end %>
  <div>
    <div><span>Privacy Policy Termes&Conditions</span> © 2020 Copyright: All rights reserved </div>
  </div>
  <div>Contact Us:
    <i class="fab fa-twitter"></i>
    <i class="fab fa-instagram"></i>
    <i class="fab fa-facebook-f"></i>
  </div>
</footer>

app/views/layouts/_login.html.erb
<%= link_to 'LOGIN', login_path %> |

app/views/layouts/_logout.html.erb
<%= link_to 'LOGOUT', logout_path, :method => :delete %>

app/views/layouts/_navigation.html.erb
<nav>
  <ul class = "nav-main">
    <li>
      <%= link_to root_path, class: "ml-lg-5" do %>
        <%= image_tag "my_logo1.jpg" %>
      <% end %>
    </li>
    <li>
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          CATEGORIES
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% Category.all.each do |category| %>
            <%= link_to category.name.upcase, category_path(category), class: 'dropdown-item'%>
          <% end %>
        </div>
      </div>
    </li>
    <li>
      <%= login_link %>
      <%= register_link %>
      <%= category_link %>
      <%= article_link %>
      <%= logout_link %>
    </li>
    <ul>
    </nav>

app/views/layouts/_register.html.erb
<%= link_to 'REGISTER', new_user_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoshanLife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/a0d360eeab.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/flash_style'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/_article_back.html.erb
<div class="jumbotron", style="background-image: url(<%=url_for(popular_article.image)%>)";>
  <h2 class="display-5 font-weight-bold"><%= popular_article.title %></h2>
  <p class="lead"><%= popular_article.body %></p>
</div>

app/views/pages/_article_title.html.erb
<h4 class = 'pt-5'><%= recent_article(category).title%></h4>

app/views/pages/home.html.erb
<%= homepage_background %>
<div class="grid-container">
  <% list_categories.each do |category|%>
    <%= link_to category_path(category) do %>
      <div class = 'box', <% if category.articles.exists? %>style="background-image: url(<%=url_for(recent_article(category).image)%>)";<%end%>>
        <h2 class = 'category-head'><%= category.name.capitalize %></h2>
        <%= check_article(category) %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_user_form.html.erb
<%= form_with(model: @user, class: 'shadow bg-secondary forms rounded', local: true) do |f|%>
  <div class = 'form-group row'>
    <%= f.label :name, class: 'col-2 col-form-label text-light'%>
    <div class = 'col-10'>
      <%= f.text_field :name, class: 'form-control shadow rounded', placeholder: 'Enter your name'%>
    </div>
  </div>
  <div class = 'form-group row'>
    <%= f.label :password, class: 'col-2 col-form-label text-light'%>
    <div class = 'col-10'>
      <%= f.password_field :password, class: 'form-control shadow rounded', placeholder: 'Enter your password'%>
    </div>
  </div>
  <div class = 'form-group row justify-content-center'>
    <%= f.submit 'Sign Up', class: 'btn btn-outline-light btn-lg' %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class = 'background', style="background-image: url(<%= asset_path 'lifestyle.jpg' %>)";>
  <div class = 'container sign-up'>
    <div class = 'row justify-content-center'>
      <div class = 'col-10'>
        <%= render 'user_form' %>
      </div>
    </div>
  </div>
</div>

app/views/votes/_vote_form.html.erb
<%= form_with(model: @vote, url: votes_path, local: true) do |form| %>
  <%= form.hidden_field :user_id, class: 'form-control', value: current_user.id %>
  <%= form.hidden_field :article_id, class: 'form-control', value: article.id %>
  <%= button_tag type: 'submit' do %>
    <i class="fa fa-thumbs-up pl-2" aria-hidden="true"></i>
  <% end %>
<% end %>